"""
OPTIMIZED FULL STACK CONFIGURATION
===================================
Generated by COLAB_FULL_STACK_OPTIMIZER.ipynb
Date: 2025-12-05T03:15:44.577328

This file contains optimized parameters for all production modules.
"""

# ==============================================================================
# FORECAST ENGINE SETTINGS
# ==============================================================================
FORECAST_CONFIG = {
    'model_type': 'HistGB',
    'horizon_days': 5,
    'prediction_threshold': 0.03,
    'decay_start_day': 5,
    'decay_rate': 0.2,
    'max_forecast_days': 24
}

# ==============================================================================
# AI RECOMMENDER SETTINGS
# ==============================================================================
AI_RECOMMENDER_CONFIG = {
    'top_features': ['atr_pct', 'ema_50', 'ema_21', 'ema_8', 'bb_width', 'obv', 'rsi_21', 'rsi_14', 'macd', 'macd_signal', 'vol_sma', 'trend_long', 'atr_14', 'rsi_7', 'cci'],
    'atr_multiplier': 0.75,
    'model_params': {'max_iter': 358, 'max_depth': 15, 'learning_rate': 0.011819161482309668, 'min_samples_leaf': 7, 'l2_regularization': 0.48339224620158877}
}

# ==============================================================================
# RISK MANAGER SETTINGS
# ==============================================================================
RISK_CONFIG = {
    'risk_per_trade': 0.015,  # 1.5%
    'max_daily_loss': 0.01,  # 1.0%
    'max_positions': 3,
    'default_stop_loss_pct': 0.05,  # 5%
    'default_take_profit_pct': 0.10  # 10%
}

# ==============================================================================
# MARKET REGIME SETTINGS
# ==============================================================================
REGIME_CONFIG = {
    'bull_threshold': 10.0,  # 21d return > X%
    'bear_threshold': -3.0,  # 21d return < X%
    'adx_trend_threshold': 30.0,
    'lookback_days': 21
}

# ==============================================================================
# COMBINED PRODUCTION STACK CONFIG
# ==============================================================================
PRODUCTION_CONFIG = {
    'forecast': FORECAST_CONFIG,
    'ai_recommender': AI_RECOMMENDER_CONFIG,
    'risk': RISK_CONFIG,
    'regime': REGIME_CONFIG
}
