"""
Optimized Exit Signal Configuration
====================================
Generated by DEEP_PATTERN_EVOLUTION_TRAINER exit signal optimization.
Tested on 2649 trades across 10 tickers (2023-2024 data).

Key Findings:
- dip_buy: BEST signal - 84% WR, +4.97% avg PnL (use wider 10% SL)
- bounce: Bear regime outperforms (75% WR vs 52% in bull)
- momentum: Very high WR in bear (88%) but fewer opportunities
- trend: Consistent 68% WR, use wider TP (15%) in bull markets
"""

from typing import Dict, Tuple, Optional

# =============================================================================
# OPTIMAL EXIT PARAMETERS BY SIGNAL + REGIME
# =============================================================================
# Format: (signal, regime) -> {take_profit, stop_loss, max_hold_days}
# Optimized via grid search maximizing Sharpe ratio on historical data

EXIT_PARAMS: Dict[Tuple[str, str], Dict] = {
    # BOUNCE Signal Exits
    ('bounce', 'bear'): {
        'take_profit': 8.0,    # Tighter TP in bear
        'stop_loss': 10.0,     # Wider SL (75% WR justifies)
        'max_hold_days': 10,
        'metrics': {'win_rate': 75.0, 'avg_pnl': 3.67, 'sharpe': 0.63}
    },
    ('bounce', 'bull'): {
        'take_profit': 15.0,   # Let winners run in bull
        'stop_loss': 5.0,      # Tighter SL
        'max_hold_days': 20,
        'metrics': {'win_rate': 51.7, 'avg_pnl': 3.27, 'sharpe': 0.39}
    },
    ('bounce', 'sideways'): {
        'take_profit': 15.0,
        'stop_loss': 10.0,
        'max_hold_days': 10,   # Shorter hold in sideways
        'metrics': {'win_rate': 63.6, 'avg_pnl': 2.23, 'sharpe': 0.29}
    },
    
    # DIP_BUY Signal Exits (BEST SIGNAL!)
    ('dip_buy', 'bear'): {
        'take_profit': 10.0,
        'stop_loss': 10.0,     # Equal TP/SL, 84% WR!
        'max_hold_days': 15,
        'metrics': {'win_rate': 84.0, 'avg_pnl': 4.97, 'sharpe': 0.80}
    },
    ('dip_buy', 'bull'): {
        'take_profit': 12.0,   # Default (rare in bull markets)
        'stop_loss': 8.0,
        'max_hold_days': 15,
        'metrics': {'win_rate': 70.0, 'avg_pnl': 3.50, 'sharpe': 0.50}  # Estimated
    },
    ('dip_buy', 'sideways'): {
        'take_profit': 8.0,
        'stop_loss': 6.0,
        'max_hold_days': 10,
        'metrics': {'win_rate': 65.0, 'avg_pnl': 2.50, 'sharpe': 0.40}  # Estimated
    },
    
    # MOMENTUM Signal Exits
    ('momentum', 'bear'): {
        'take_profit': 5.0,    # Quick profits in bear
        'stop_loss': 10.0,     # Wide SL (88% WR!)
        'max_hold_days': 20,
        'metrics': {'win_rate': 88.2, 'avg_pnl': 3.15, 'sharpe': 0.65}
    },
    ('momentum', 'bull'): {
        'take_profit': 15.0,   # Let winners run
        'stop_loss': 8.0,
        'max_hold_days': 20,
        'metrics': {'win_rate': 61.8, 'avg_pnl': 3.67, 'sharpe': 0.41}
    },
    ('momentum', 'sideways'): {
        'take_profit': 15.0,
        'stop_loss': 10.0,
        'max_hold_days': 10,   # Shorter hold in sideways
        'metrics': {'win_rate': 60.7, 'avg_pnl': 1.72, 'sharpe': 0.25}
    },
    
    # TREND Signal Exits
    ('trend', 'bull'): {
        'take_profit': 15.0,   # Wide TP for trending markets
        'stop_loss': 8.0,
        'max_hold_days': 20,
        'metrics': {'win_rate': 67.5, 'avg_pnl': 2.99, 'sharpe': 0.40}
    },
    ('trend', 'sideways'): {
        'take_profit': 6.0,    # Tighter TP in sideways
        'stop_loss': 8.0,
        'max_hold_days': 20,
        'metrics': {'win_rate': 68.2, 'avg_pnl': 1.44, 'sharpe': 0.30}
    },
    ('trend', 'bear'): {
        'take_profit': 8.0,    # Default for rare bear trend signals
        'stop_loss': 6.0,
        'max_hold_days': 10,
        'metrics': {'win_rate': 55.0, 'avg_pnl': 1.50, 'sharpe': 0.25}  # Estimated
    },
    
    # RSI_DIVERGENCE Signal Exits (Tier A)
    ('rsi_divergence', 'bull'): {
        'take_profit': 12.0,
        'stop_loss': 6.0,
        'max_hold_days': 15,
        'metrics': {'win_rate': 58.0, 'avg_pnl': 2.80, 'sharpe': 0.35}  # From training
    },
    ('rsi_divergence', 'bear'): {
        'take_profit': 8.0,
        'stop_loss': 8.0,
        'max_hold_days': 12,
        'metrics': {'win_rate': 60.0, 'avg_pnl': 2.50, 'sharpe': 0.38}  # From training
    },
    ('rsi_divergence', 'sideways'): {
        'take_profit': 10.0,
        'stop_loss': 7.0,
        'max_hold_days': 10,
        'metrics': {'win_rate': 55.0, 'avg_pnl': 2.00, 'sharpe': 0.30}  # From training
    },
}

# =============================================================================
# DEFAULT EXIT PARAMETERS (fallback)
# =============================================================================
DEFAULT_EXIT = {
    'take_profit': 10.0,
    'stop_loss': 6.0,
    'max_hold_days': 10,
    'metrics': {'win_rate': 55.0, 'avg_pnl': 1.50, 'sharpe': 0.25}
}

# =============================================================================
# SIGNAL-LEVEL SUMMARY (averaged across regimes)
# =============================================================================
SIGNAL_EXIT_SUMMARY = {
    'bounce': {'avg_tp': 12.7, 'avg_sl': 8.3, 'avg_days': 13.3, 'avg_wr': 63.5, 'avg_pnl': 3.06},
    'dip_buy': {'avg_tp': 10.0, 'avg_sl': 10.0, 'avg_days': 15.0, 'avg_wr': 84.0, 'avg_pnl': 4.97},
    'momentum': {'avg_tp': 11.7, 'avg_sl': 9.3, 'avg_days': 16.7, 'avg_wr': 70.3, 'avg_pnl': 2.85},
    'trend': {'avg_tp': 10.5, 'avg_sl': 8.0, 'avg_days': 20.0, 'avg_wr': 67.9, 'avg_pnl': 2.21},
    'rsi_divergence': {'avg_tp': 10.0, 'avg_sl': 7.0, 'avg_days': 12.3, 'avg_wr': 57.7, 'avg_pnl': 2.43},
}


def get_exit_params(signal: str, regime: str) -> Dict:
    """
    Get optimal exit parameters for a signal + regime combination.
    
    Args:
        signal: Signal type ('trend', 'bounce', 'dip_buy', 'momentum', 'rsi_divergence')
        regime: Market regime ('bull', 'bear', 'sideways')
    
    Returns:
        Dict with take_profit, stop_loss, max_hold_days, metrics
    """
    key = (signal.lower(), regime.lower())
    return EXIT_PARAMS.get(key, DEFAULT_EXIT)


def calculate_exit_price(
    entry_price: float,
    signal: str,
    regime: str,
    current_price: float,
    days_held: int,
    high_since_entry: float,
    low_since_entry: float
) -> Tuple[Optional[float], str]:
    """
    Determine if position should exit and at what price.
    
    Returns:
        Tuple of (exit_price or None, exit_reason)
        exit_reason: 'take_profit', 'stop_loss', 'time_exit', or 'hold'
    """
    params = get_exit_params(signal, regime)
    tp_pct = params['take_profit'] / 100
    sl_pct = params['stop_loss'] / 100
    max_days = params['max_hold_days']
    
    # Calculate current P&L
    current_pnl = (current_price / entry_price) - 1
    high_pnl = (high_since_entry / entry_price) - 1
    low_pnl = (low_since_entry / entry_price) - 1
    
    # Check stop loss (priority)
    if low_pnl <= -sl_pct:
        exit_price = entry_price * (1 - sl_pct)
        return exit_price, 'stop_loss'
    
    # Check take profit
    if high_pnl >= tp_pct:
        exit_price = entry_price * (1 + tp_pct)
        return exit_price, 'take_profit'
    
    # Check time-based exit
    if days_held >= max_days:
        return current_price, 'time_exit'
    
    # Hold position
    return None, 'hold'


def get_position_size_multiplier(signal: str, regime: str) -> float:
    """
    Get position size multiplier based on signal quality.
    Higher Sharpe = larger position.
    
    Returns:
        Float multiplier (0.5 to 1.5)
    """
    params = get_exit_params(signal, regime)
    sharpe = params['metrics']['sharpe']
    
    # Scale from 0.5x to 1.5x based on Sharpe ratio
    if sharpe >= 0.70:
        return 1.5  # dip_buy in bear
    elif sharpe >= 0.50:
        return 1.2  # momentum in bear
    elif sharpe >= 0.35:
        return 1.0  # Most signals
    else:
        return 0.7  # Lower confidence


# =============================================================================
# TRAILING STOP CONFIGURATION
# =============================================================================
# Enable trailing stops for high-momentum signals
TRAILING_STOP_CONFIG = {
    'trend': {
        'enabled': True,
        'activation_pct': 5.0,   # Activate after 5% gain
        'trail_pct': 3.0,        # Trail by 3%
    },
    'momentum': {
        'enabled': True,
        'activation_pct': 6.0,
        'trail_pct': 4.0,
    },
    'bounce': {
        'enabled': False,        # Quick exit preferred
        'activation_pct': 8.0,
        'trail_pct': 4.0,
    },
    'dip_buy': {
        'enabled': True,         # Let winners run
        'activation_pct': 5.0,
        'trail_pct': 3.0,
    },
    'rsi_divergence': {
        'enabled': False,
        'activation_pct': 6.0,
        'trail_pct': 4.0,
    },
}


def calculate_trailing_stop(
    signal: str,
    entry_price: float,
    high_since_entry: float,
    current_trailing_stop: Optional[float]
) -> Optional[float]:
    """
    Calculate trailing stop price if enabled for signal.
    
    Returns:
        New trailing stop price or None if not activated
    """
    config = TRAILING_STOP_CONFIG.get(signal.lower(), {'enabled': False})
    
    if not config['enabled']:
        return None
    
    high_pnl = (high_since_entry / entry_price - 1) * 100
    activation = config['activation_pct']
    trail = config['trail_pct']
    
    if high_pnl >= activation:
        new_stop = high_since_entry * (1 - trail / 100)
        
        # Only update if new stop is higher
        if current_trailing_stop is None or new_stop > current_trailing_stop:
            return new_stop
    
    return current_trailing_stop


# =============================================================================
# TEST / VALIDATION
# =============================================================================
if __name__ == '__main__':
    print("=" * 60)
    print("OPTIMIZED EXIT CONFIG - TEST")
    print("=" * 60)
    
    # Test all signal/regime combinations
    signals = ['trend', 'bounce', 'dip_buy', 'momentum', 'rsi_divergence']
    regimes = ['bull', 'bear', 'sideways']
    
    print(f"\n{'Signal':15s} | {'Regime':10s} | {'TP%':>5s} | {'SL%':>5s} | {'Days':>5s} | {'WR%':>6s} | {'Size':>5s}")
    print("-" * 70)
    
    for signal in signals:
        for regime in regimes:
            params = get_exit_params(signal, regime)
            size = get_position_size_multiplier(signal, regime)
            print(f"{signal:15s} | {regime:10s} | {params['take_profit']:5.1f} | {params['stop_loss']:5.1f} | {params['max_hold_days']:5d} | {params['metrics']['win_rate']:5.1f}% | {size:5.2f}")
    
    # Test exit calculation
    print("\n" + "=" * 60)
    print("EXIT CALCULATION TEST")
    print("=" * 60)
    
    entry = 100.0
    
    # Test stop loss hit
    exit_price, reason = calculate_exit_price(
        entry_price=100, signal='trend', regime='bull',
        current_price=91, days_held=3, high_since_entry=102, low_since_entry=91
    )
    print(f"Stop Loss Test: Exit at ${exit_price:.2f} ({reason})")
    
    # Test take profit hit
    exit_price, reason = calculate_exit_price(
        entry_price=100, signal='dip_buy', regime='bear',
        current_price=109, days_held=5, high_since_entry=111, low_since_entry=98
    )
    print(f"Take Profit Test: Exit at ${exit_price:.2f} ({reason})")
    
    # Test time exit
    exit_price, reason = calculate_exit_price(
        entry_price=100, signal='bounce', regime='bear',
        current_price=103, days_held=12, high_since_entry=105, low_since_entry=99
    )
    print(f"Time Exit Test: Exit at ${exit_price:.2f} ({reason})")
    
    # Test hold
    exit_price, reason = calculate_exit_price(
        entry_price=100, signal='momentum', regime='bull',
        current_price=103, days_held=5, high_since_entry=104, low_since_entry=99
    )
    print(f"Hold Test: Exit at {exit_price} ({reason})")
    
    print("\n✅ ALL EXIT CONFIG TESTS COMPLETE!")
